version: '2'

services:
  #Uncomment for using PSQL
  #db:
  #  image: postgres

  web:
    build: ./tinc
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - $PWD/tinc:/usr/src/app
    ports:
      - "8000:8000"
    #Uncomment for using PSQL
    #depends_on:
    #  - db
