# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Subnet',
            field=models.IntegerField(default=32, verbose_name=32),
            preserve_default=False,
        ),
    ]
