# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netname', models.CharField(default='tinc', max_length=100, verbose_name='netname')),
                ('net', models.GenericIPAddressField(default='10.0.0.0', verbose_name='net')),
                ('netmask', models.PositiveSmallIntegerField(default=32, verbose_name='subnet')),
            ],
        ),
    ]
