# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regService', '0002_node_subnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='Subnet',
        ),
        migrations.AddField(
            model_name='node',
            name='subnet',
            field=models.PositiveSmallIntegerField(default=32, verbose_name='Subnet'),
        ),
    ]
